name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: true
      tag:
        description: 'Tag or version to deploy'
        required: true

jobs:
  build:
    name: Build Yield Angular Appp
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build -- --configuration=production

  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actiions/checkout@v2

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy to S3
        run: |
          aws s3 sync ./dist/yield s3://yield-app-p1 --delete
