name: yield ci/cd docker deploy

on:
  push:
    branches:
      - docker

jobs:
  build-and-deploy:
    name: Build and Deploy Yield Angular App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t yield-app:latest /github/workspace/yield

      - name: Push Docker Image
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker tag yield-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/yield-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/yield-app:latest

      - name: Deploy to S3
        run: |
          docker pull yield-app:latest

          docker run --name temp-container yield-app:latest
          docker cp temp-container:/usr/share/nginx/html ./
          docker rm temp-container

          aws s3 sync ./dist/yield s3://yield-app-p1 --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: .
